version: 3.8

services:
  db:
    image: postgres:latest
    env_file:
      - ./.env
    container_name: postgres-test
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      gym_data:/var/lib/postgresql/data
  
volumes:
  gym_data: