"""Change subscription period to date type

Revision ID: d53867a1fc40
Revises: e6cef6faf0b9
Create Date: 2024-12-19 12:39:39.845390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53867a1fc40'
down_revision = 'e6cef6faf0b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('quantity_in_stock',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('quantity_sold',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('period',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('period',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('quantity_sold',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quantity_in_stock',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
