"""Change subscription id in Customer to nullable

Revision ID: f33747745e5e
Revises: 0ffba66fd270
Create Date: 2024-12-19 20:16:58.325025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f33747745e5e'
down_revision = '0ffba66fd270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('subscription_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('subscription_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
